### ISSUE TITLE
Problem running tests

### ISSUE THREAD

**Issue by hypexr** [PDMLab/massive-migrate#12]
When I run the tests I'm getting this output:

```
npm test

> massive-migrate@0.8.1 test /Users/scott/projects/massive-migrate
> mocha test/test.js



  when migrating from an empty database to first version
    1) should create pgmigration table
    2) "before each" hook: removeTables for "should create customer table"

  when migrating from version 0.1.0 to version 0.2.0
    3) "before each" hook: removeTables for "should run second migration"


  0 passing (6s)
  3 failing

  1) when migrating from an empty database to first version should create pgmigration table:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


  2) when migrating from an empty database to first version "before each" hook: removeTables for "should create customer table":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.


  3) when migrating from version 0.1.0 to version 0.2.0 "before each" hook: removeTables for "should run second migration":
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.

```

It looks like the connection string in test.js expects to connect to a db named "postgres" w/ user "postgres" and password "postgres".  I've created the DB and user and can login as that user and create / drop tables.  My postgres instance is running on 5432. Is there additional configuration that I'm missing.

Thanks!

**Comment by AlexZeitler** [comment]
Just tried it as described with Postgres in a Docker container with Node 4.2.3:

Ran `npm run dockerpostgres` followed by `npm test`

Output:

when migrating from an empty database to first version
    ✓ should create pgmigration table (215ms)
    ✓ should create customer table (238ms)
    ✓ should create salutation table (210ms)
    ✓ should pass options user defined options for particular migration to up script (218ms)

  when migrating from version 0.1.0 to version 0.2.0
    ✓ should run second migration (317ms)
    ✓ should insert second migration to pgmigration table (264ms)
    ✓ should return an error if migration is executed twice (356ms)

Because I didn't specify a particular Postgres version, Docker has been installing 9.5.3

On my dev machine I also have a PostgreSQL 9.4 installed, which I started and after npm test, I got this:

⋙  npm test

> massive-migrate@0.8.1 test /home/alex/src/massive-migrate
> mocha test/test.js

  when migrating from an empty database to first version
    ✓ should create pgmigration table (221ms)
    ✓ should create customer table (187ms)
    ✓ should create salutation table (192ms)
    ✓ should pass options user defined options for particular migration to up script (224ms)

  when migrating from version 0.1.0 to version 0.2.0
    ✓ should run second migration (326ms)
    ✓ should insert second migration to pgmigration table (233ms)
    ✓ should return an error if migration is executed twice (275ms)

  7 passing (2s)

Because the Docker version is a plain "install" using database, user and password "postgres" there must be another reason why tests fail.

Which Node.js version do you use?

**Comment by AlexZeitler** [comment]
Just tried it using Node 6.2.1 and it also works.

**Comment by hypexr** [comment]
node 4.2.3. Are you running the test with the local postgres install (not docker) using un/pw/db names "postgres"?

**Comment by AlexZeitler** [comment]
Yes, just verified it again using pgAdminIII

**Comment by hypexr** [comment]
Found the error to be:

Error: permission denied to create extension "uuid-ossp"

and fixed by modifying my postgres user to have the SUPERUSER role.
